name: Run tests

on:
  push:
    branches-ignore:
      - "feat/**"
      - "fix/**"
  pull_request:
    branches:
      - "develop"

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: ./gradlew test